time_reporting/time_reporting/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('user_auth.urls')),
    path('timelog/', include(('timelog.urls', 'timelog'), namespace='timelog')),
    path('admin/', admin.site.urls),
]

time_reporting/timelog/urls.py
from django.urls import path
from . import views

app_name = "timelog"
urlpatterns = [
    path('', views.index, name='index'),
    path('submit/', views.create, name='create'),
    path('update/<int:pk>', views.update, name='update'),

]

time_reporting/timelog/models.py
from django.db import models
from user_auth.models import Employee



# Create your models here.
class Hours(models.Model):

    MONTHS = (
        ('01', 'JAN'),
        ('02', 'FEB'),
        ('03', 'MAR'),
        ('04', 'APR'),
        ('05', 'MAY'),
        ('06', 'JUN'),
        ('07', 'JUL'),
        ('08', 'AUG'),
        ('09', 'SEP'),
        ('10', 'OCT'),
        ('11', 'NOV'),
        ('12', 'DEC')
    )
    YEARS = (
        ('2015', '2015'),
        ('2016', '2016'),
        ('2017', '2017'),
        ('2018', '2018'),
        ('2019', '2019'),
        ('2020', '2020')
        )
    STATUS = (
        ('Pending', 'Pending'),
        ('Submitted', 'Submitted'),
        ('Completed', 'Completed')
    )

    reference_pk = models.ForeignKey(Employee, on_delete=models.CASCADE)
    month = models.CharField(max_length=2, choices=MONTHS, default='JAN')
    year = models.CharField(max_length=4, choices=YEARS, default='2020')
    submitting_date = models.DateTimeField(auto_now_add=True)
    total_hours = models.DecimalField(max_digits=5, decimal_places=2)
    week1 = models.DecimalField(max_digits=4, decimal_places=2)
    week2 = models.DecimalField(max_digits=4, decimal_places=2)
    week3 = models.DecimalField(max_digits=4, decimal_places=2)
    week4 = models.DecimalField(max_digits=4, decimal_places=2)
    status = models.CharField(max_length=20, choices=STATUS, default='Pending')


    class Meta:
        verbose_name_plural = "Hours"

    def __str__(self):
        return "%s_%s-%s" %(self.reference_pk, self.month, self.year)

time_reporting/timelog/forms.py
from django import forms
from .models import Hours
from time_reporting.settings import MAX_HOURS
import logging

logger_e = logging.getLogger('errors')

class TimesheetForm(forms.ModelForm):

    month = forms.ChoiceField(choices=Hours.MONTHS)
    class Meta:
        model = Hours
        fields = [
            'month',
            'year',
            'total_hours',
            'week1',
            'week2',
            'week3',
            'week4'
        ]

    def clean_week1(self):
        week1 = self.cleaned_data['week1']
        if week1 > MAX_HOURS:
            logger_e.error("Total hours for week1 exceeded it's limit")
            raise forms.ValidationError("Total hours for week1 exceeded it's limit")
        return week1

    def clean_week2(self):
        week2 = self.cleaned_data['week2']
        if week2 > MAX_HOURS:
            logger_e.error("Total hours for week2 exceeded it's limit")
            raise forms.ValidationError("Total hours for week2 exceeded it's limit")
        return week2

    def clean_week3(self):
        week3 = self.cleaned_data['week3']
        if week3 > MAX_HOURS:
            logger_e.error("Total hours for week3 exceeded it's limit")
            raise forms.ValidationError("Total hours for week3 exceeded it's limit")
        return week3

    def clean_week4(self):
        week4 = self.cleaned_data['week4']
        if week4 > MAX_HOURS:
            logger_e.error("Total hours for week4 exceeded it's limit")
            raise forms.ValidationError("Total hours for week4 exceeded it's limit")
        return week4

time_reporting/timelog/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .forms import TimesheetForm
from user_auth.views import get_user
from user_auth.models import Employee
from .models import Hours
from time_reporting import settings
import logging

# Get an instance of a logger
logger = logging.getLogger(__name__)
logger_e = logging.getLogger('errors')

# Create your views here.

# Function for homepage
def index(request, *args, **kwargs):
    form = TimesheetForm(request.POST or None)
    context = {}
    context['reporting_year'], context['reporting_month'] = month_year(settings.REPORTING_DATE)
    if 'user_id' in request.session:
        user = get_user(request)
        context['user'] = user
        logger.info("Employee name:" + user.name)
        try:
            data = Hours.objects.filter(reference_pk=Employee.objects.get(reference=request.session['user_id']))
        except Hours.DoesNotExist:
            data = None
        return render(request, 'timelog/index.html', {'form': form, 'data': data, 'context': context})
    return redirect('loginto')

# Function to submit a new timesheet
def create(request, *args, **kwargs):
    form = TimesheetForm(request.POST or None)
    if 'user_id' in request.session:
        user = get_user(request)
        context = {}
        context['reporting_year'], context['reporting_month'] = month_year(settings.REPORTING_DATE)
        context['m'] = request.GET.get('month')
        context['y'] = request.GET.get('year')
        context['user'] = user
        logger.info("Employee name:" + user.name)
        try:
            data = Hours.objects.filter(reference_pk=user.reference, month=request.GET.get('month'), year=request.GET.get('year'))
        except Hours.DoesNotExist:
            data = None
        if form.is_valid():
            time = form.save(commit=False)
            time.reference_pk = Employee.objects.get(reference=request.session['user_id'])
            time.save()
            hours = Hours.objects.filter(reference_pk=request.session['user_id'], month=time.month, year=time.year).update(status="Submitted")
            success = "Timesheet submitted successfully"
            logger.info("Month: " + time.month + " " + "Year: " + time.year +
                        '\n' + "Week1: " + str(time.week1) + " " + "Week2: " + str(time.week2) + " " +
                        "Week3: " + str(time.week3) + " " + "Week4: " + str(time.week4) +
                        '\n' + "Total Hours: " + str(time.total_hours))
            logger.info("Timesheet submitted successfully")
            return redirect('timelog:index')
    return render(request, 'timelog/sheet.html', {'form': form, 'context': context, 'data': data})

# Function to update a submitted timesheet.
def update(request, pk):
    form = TimesheetForm()
    context = {}
    if 'user_id' in request.session:
        context['user'] = get_user(request)
        logger.info("Employee name:" + context['user'].name)
        hour = get_object_or_404(Hours, pk=pk)
        form = TimesheetForm(request.POST or None, instance=hour)
        context['pk'] = pk
        context['year'], context['month'] = hour.year, hour.month
        context['reporting_year'], context['reporting_month'] = month_year(settings.REPORTING_DATE)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            logger.info("Month: " + obj.month + " " + "Year: " + obj.year +
                        '\n' + "Week1: " + str(obj.week1) + " " + "Week2: " + str(obj.week2) + " " +
                        "Week3: " + str(obj.week3) + " " + "Week4: " + str(obj.week4) +
                        '\n' + "Total Hours: " + str(obj.total_hours))
            logger.info("Timesheet updated successfully")
            return redirect('timelog:index')
    return render(request, 'timelog/update.html', {'form': form, 'context': context} )

# This is to restrict the month and year based on the REPORTING_DATE
def month_year(reporting_date):
    year = reporting_date[:4]
    month = reporting_date[5:7]
    return year, month

time_reporting/timelog/templates/timelog/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'timelog/css/index.css' %}">

<div class="container">
  <h1>Monthly Employee Timesheet</h1>
  <p>Employee Name: <b>{{ context.user.name }}</b> <a href="{% url 'logout' %}">Logout</a></p>
  <div class="form-group">
    <form method="get" action="{% url 'timelog:create'%}">
    {% csrf_token %}
    <div class="my">
      <p>{{ form.month.label_tag }}
        <select name="month">
          {% for choice in form.fields.month.choices %}
          {% if choice.0 < context.reporting_month %}
          <option value="{{ choice.0 }}" name="monthId">{{ choice.1 }}</option>
          {% endif %}
          {% endfor %}
        </select>
        {{ form.year.label_tag }}
        <select name="year">
          {% for choice in form.year.field.choices %}
          {% if choice.0 <= context.reporting_year %}
          <option value="{{ choice.0 }}">{{ choice.1 }}</option>
          {% endif %}
          {% endfor %}
        </select>
        <button type="submit"> Submit your timesheet</button>
      </p>
    </div>
  </div>

  <table id="status">
    <tr>
      <th>Month</th>
      <th>Year</th>
      <th>Status</th>
    </tr>
    {% for d in data %}
    <tr>
    <td>{{ d.month }}</td>
    <td>{{ d.year }}</td>
    {% if d.status == 'Submitted' %}
    <td><a href="{% url 'timelog:update' pk=d.id %}">{{ d.status }}</a></td>
    {% else %}
    <td>{{ d.status }}</td>
    {% endif %}
    </tr>
    {% endfor %}
  </table>
</div>

{% endblock %}

time_reporting/timelog/templates/timelog/sheet.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'timelog/css/sheet.css' %}">

<div class="container">
  <h1>Monthly Employee Timesheet</h1>
  <p>Employee Name: <b>{{ context.user.name }}</b></p>
  <div class="form-group">
    <form method="post" action="{% url 'timelog:create' %}">
    {% csrf_token %}
    <div class="my">
      <p>{{ form.month.label_tag }}
        <select name="month" id="month">
          <option value="{{ context.m }}" selected>
          {{ context.m }}
          </option>
        </select>
        {{ form.year.label_tag }}
        <select name="year" id="year">
          <option value="{{ context.y }}" selected>
          {{ context.y }}
          </option>
        </select>
      </p>
    </div>

    <table id="sheet">
      <tr>
        <th>Weeks</th>
        <th>Hours</th>
      </tr>
      {% if data %}
        {% for d in data %}
      <tr>
        <td>{{ form.week1.label }}</td>
        <td>{{ d.week1 }}</td>
      </tr>
      <tr>
        <td>{{ form.week2.label }}</td>
        <td>{{ d.week2 }}</td>
      </tr>
      <tr>
        <td>{{ form.week3.label }}</td>
        <td>{{ d.week3 }}</td>
      </tr>
      <tr>
        <td>{{ form.week4.label }}</td>
        <td>{{ d.week4 }}</td>
      </tr>
      <tr>
        <td>{{ form.total_hours.label }}</td>
        <td>{{ d.total_hours }}</td>
      </tr>
      <p>{{ form.status.label_tag }}{% if d.status == "Submitted" %}If you want to edit the timesheet, please go<a href="{% url 'timelog:update' pk=d.id %}"> here</a>{% else %}Your timesheet has been marked as {{ d.status }}{% endif %}</p>
      {% endfor %}
      {% else %}
      <tr>
        <td>{{ form.week1.label }}</td>
        <td>{{ form.week1 }}<span class="red" style="color:red;">{{ form.week1.errors|striptags }}</span></td>
      </tr>
      <tr>
        <td>{{ form.week2.label }}</td>
        <td>{{ form.week2 }}<span class="red" style="color:red;">{{ form.week2.errors|striptags }}</span></td>
      </tr>
      <tr>
        <td>{{ form.week3.label }}</td>
        <td>{{ form.week3 }}<span class="red" style="color:red;">{{ form.week3.errors|striptags }}</span></td>
      </tr>
      <tr>
        <td>{{ form.week4.label }}</td>
        <td>{{ form.week4 }}<span class="red" style="color:red;">{{ form.week4.errors|striptags }}</span></td>
      </tr>
      <tr>
        <td>{{ form.total_hours.label }}</td>
        <td>{{ form.total_hours }}</td>
      </tr>
      <tr>
      <td colspan="2" text-align="center"><div class="submit-button" align-items="center"><button type="submit" id="submit_button">Submit Timesheet</button></div></td>
      </tr>
      {% endif %}
    </table>
    <a href="{% url 'timelog:index' %}">Back to Home</a>
    <div>
    {% if success %}
    {{ success }}
    {% endif %}
    </div>
  </div>

</div>
{% endblock %}

time_reporting/timelog/templates/timelog/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'timelog/css/sheet.css' %}">

<div class="container">
  <h1>Monthly Employee Timesheet</h1>
  <h3>Update</h3>
  <p>Employee Name: <b>{{ context.user.name }}</b></p>
  <div class="form-group">
    <form method="post" action="{% url 'timelog:update' pk=context.pk %}">
    {% csrf_token %}
    <div class="my">
      <p>{{ form.month.label_tag }}
        <select name="month" id="month">
          <option value="{{ context.month }}" selected>
          {{ context.month }}
          </option>
        </select>
        {{ form.year.label_tag }}
        <select name="year" id="year">
          <option value="{{ context.year }}" selected>
          {{ context.year }}
          </option>
        </select>
      </p>
    </div>
    </div>

    <table id="sheet">
      <tr>
        <th>Weeks</th>
        <th>Hours</th>
      </tr>
    <tr>
      <td>{{ form.week1.label }}</td>
      <td>{{ form.week1 }}<span class="red" style="color:red;">{{ form.week1.errors|striptags }}</span></td>
    </tr>
    <tr>
      <td>{{ form.week2.label }}</td>
      <td>{{ form.week2 }}<span class="red" style="color:red;">{{ form.week2.errors|striptags }}</span></td>
    </tr>
    <tr>
      <td>{{ form.week3.label }}</td>
      <td>{{ form.week3 }}<span class="red" style="color:red;">{{ form.week3.errors|striptags }}</span></td>
    </tr>
    <tr>
      <td>{{ form.week4.label }}</td>
      <td>{{ form.week4 }}<span class="red" style="color:red;">{{ form.week4.errors|striptags }}</span></td>
    </tr>
    <tr>
      <td>{{ form.total_hours.label }}</td>
      <td>{{ form.total_hours }}</td>
    </tr>
    <tr>
    <td colspan="2" text-align="center"><div class="submit-button" align-items="center"><button type="submit" id="submit_button">Update Timesheet</button></div></td>
    </tr>
    </table>
    <a href="{% url 'timelog:index' %}">Back to Home</a>
    <div>
    </div>
  </div>
</div>
{% endblock %}